[package]
name = "practice-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
#futures = "0.3.27"
#tokio = { version = "1.26.0", features = ["full"] }
